# Generated by Django 3.0.5 on 2020-05-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentance_type', models.CharField(max_length=200)),
                ('grammar_type', models.CharField(max_length=200)),
                ('interrogative_type', models.CharField(max_length=200)),
                ('exclamatory_type', models.CharField(max_length=200)),
                ('sentance', models.CharField(max_length=200)),
            ],
        ),
    ]
